### PR TITLE
Enable fetching retried GitLab jobs

### LINKED ISSUE #86: (Optionally) include retried GitLab jobs
At HackerOne we are interested in how many pipelines in the CI/CD are considered flaky, with flaky being defined as:

```sql
pipelines.status = 'success' AND
jobs.status != 'success' AND jobs.status != 'skipped' AND jobs.status != 'manual'
```

Currently this logic does not really work, because the default of the GitLab jobs api is to only return successful jobs (https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs) but we are also interested in retried jobs defined with parameter `include_retried `.

### PR DESCRIPTION
**Pull request by mvgijssel**
fixes #86

### CODE REVIEW

**Review by ericboucher — APPROVED** [review]

**Comment by ericboucher** [comment]
Thanks @mvgijssel. Looks like a reasonable addition. If you're ok with it, I'd prefer to merge this to the `main` branch directly. Let me know if that works for you,

**Comment by mvgijssel** [comment]
> Thanks @mvgijssel. Looks like a reasonable addition. If you're ok with it, I'd prefer to merge this to the `main` branch directly. Let me know if that works for you,

Sure no problem!

**Comment by ericboucher** [comment]
Thanks! Do you mind rebasing/restarting from `main`?. Let me know if you need a hand :)

**Comment by tayloramurphy** [comment]
@ericboucher is this PR still relevant?

**Comment by glauberferreiranees** [comment]
> @ericboucher is this PR still relevant?

Yes. Extremely relevant for me. Is there a plan to release a new version with this PR?

**Comment by edgarrmondragon** [comment]
> > @ericboucher is this PR still relevant?
> 
> Yes. Extremely relevant for me. Is there a plan to release a new version with this PR?

@glauberferreiranees I can review a new PR that fixes the merge conflicts if you're interested :)

**Comment by glauberferreiranees** [comment]
> > > @ericboucher is this PR still relevant?
> > 
> > 
> > Yes. Extremely relevant for me. Is there a plan to release a new version with this PR?
> 
> @glauberferreiranees I can review a new PR that fixes the merge conflicts if you're interested :)

I would be extremely grateful @edgarrmondragon

**Comment by edgarrmondragon** [comment]
@glauberferreiranees Great! I'll be on the lookout for your PR.

**Comment by edgarrmondragon** [comment]
Superseded by #107

**Pull request closed without merging**
